name: Regenerate LDraw complete.zip
on:
  workflow_dispatch:
  schedule:
    - cron: '40 1 * * 0' # 01:40 on Sundays

jobs:
  regenerate:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Set tag name
      shell: bash
      run: |
        NOW="$(date +'%Y.%m.%d-%H:%M')"
        echo "RELEASE_NAME=${NOW/-/ }" >> $GITHUB_ENV
        echo "TAG_NAME=v${NOW/:/.}" >> $GITHUB_ENV

    - name: Checkout BrickStore
      run: |
        mkdir -p temp
        cd temp
        git clone --depth 1 --filter=blob:none --sparse https://github.com/rgriebl/brickstore.git
        cd brickstore
        git sparse-checkout set --no-cone /ldraw
      shell: bash

    - name: Update Mappings
      shell: bash
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt -y update
        sudo DEBIAN_FRONTEND=noninteractive apt -y install python3-cbor2 python3-tqdm
        ./temp/brickstore/ldraw/create-bricklink-ldraw-id-mappings.py \
            -t temp \
            -a temp/brickstore/ldraw/mappings \
            -o complete.zip \
            2>&1  | tee regenerate.log

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "complete.zip,regenerate.log"
        commit: main
        tag: ${{ env.TAGNAME }}
        name: ${{ env.RELEASE_NAME }}
